Models/ErrorViewModel.cs
namespace magaApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/User.cs
namespace magaApp.Models
{
    public class User
    {
        public int IdUser { get; set; }

        public string FullName { get; set; }

        public string Email { get; set; }

        public string Password { get; set; }
    }
}

ViewModels/ExplorerViewModel.cs
namespace magaApp.ViewModels
{
    public class ExplorerViewModel
    {
        public int IdUser { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }

       
        public string Initials
        {
            get
            {
                if (string.IsNullOrEmpty(FullName))
                    return "";

                var names = FullName.Split(' ');
                var initials = names.Length > 1 ? $"{names[0][0]}{names[1][0]}" : names[0].Substring(0, 1);
                return initials.ToUpper();
            }
        }
    }
}

ViewModels/LoginViewModels.cs
namespace magaApp.ViewModels
{
    public class LoginViewModels
    {
        public string Email { get; set; }
        public string Password { get; set; }

    }
}

ViewModels/UserViewModels.cs
namespace magaApp.ViewModels
{
    public class UserViewModels
    {

        public string FullName { get; set; }

        public string Email { get; set; }

        public string Password { get; set; }

        public string ConfirmPassword { get; set; }


    }
}

Controllers/AccessController.cs
using Microsoft.AspNetCore.Mvc;
using magaApp.Data;
using magaApp.Models;
using Microsoft.EntityFrameworkCore;
using magaApp.ViewModels;

using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;


namespace magaApp.Controllers
{
    public class AccessController : Controller
    {
        private readonly AppDBContext _appDbContext;
        public AccessController(AppDBContext appDBContext)
        {
            _appDbContext = appDBContext;
        }

        [HttpGet]
        public IActionResult Signup()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Signup(UserViewModels model)
        {
            if (model.Password != model.ConfirmPassword)
            {
                ViewData["Message"] = "Passwords do not match 🙂";
                return View();
            }

            User user = new User()
            {
                FullName = model.FullName,
                Email = model.Email,
                Password = model.Password,
            };

            await _appDbContext.Users.AddAsync(user);
            await _appDbContext.SaveChangesAsync();

            if (user.IdUser != 0) return RedirectToAction("Login","Access");

            ViewData["Message"] = "Cannot create user";

            return View();
        }

        [HttpGet]
        public IActionResult Login()
        {
            if (User.Identity!.IsAuthenticated) return RedirectToAction("index", "Home");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModels model)
        {
            User? user_found = await _appDbContext.Users
                                .Where(u =>
                                u.Email == model.Email &&
                                u.Password == model.Password
                                ).FirstOrDefaultAsync();

            if (user_found == null)
            {
                ViewData["Message"] = "No matches found";

                return View();
            }

            List<Claim> claims = new List<Claim>()
            {
                new Claim(ClaimTypes.Name, user_found.FullName)
            };

            ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            AuthenticationProperties properties = new AuthenticationProperties()
            {
                AllowRefresh = true,
            };

            await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity),
                properties
                );

            return RedirectToAction("Index", "Home");
        }
    }
}

Controllers/HomeController.cs
using magaApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using magaApp.Data;
using magaApp.ViewModels;

namespace magaApp.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly AppDBContext _appDbContext;
        public HomeController(ILogger<HomeController> logger, AppDBContext appDbContext)
        {
            _logger = logger;
            _appDbContext = appDbContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Explorer()
        {
            
            List<User> users = _appDbContext.Users.ToList();

            
            List<ExplorerViewModel> viewModel = users.Select(u => new ExplorerViewModel
            {
                IdUser = u.IdUser,
                FullName = u.FullName,
                Email = u.Email
            }).ToList();

            return View(viewModel);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public async Task<IActionResult>GoOut()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Login", "Access");
        }
    }
}

Controllers/MagazineController.cs
using Microsoft.AspNetCore.Mvc;

namespace magaApp.Controllers
{
    public class MagazineController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}
 

Views/Access/Login.cshtml
@model magaApp.ViewModels.LoginViewModels
@{
    Layout = null;
}


<html>
<head>
    <title>Login</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="~/css/site.css" />

</head>

<body>

    <div class="container-fluid full-height">
        <div class="row h-100">
          
            <div class="d-none d-lg-block col-lg-6 p-0">
                <img src="~/images/banner.png" alt="Banner" class="img-fluid w-100 h-100" style="object-fit: cover;">
            </div>

           
            <div class="col-lg-6 col-12 d-flex align-items-center justify-content-center">
                <div class="col-lg-8 col-md-10 col-12">
                    <div class="">
                        <div class="card-header">
                            <h2 class="mb-3">Login to your Account</h2>
                            <p>See what is going on with your business</p>
                        </div>
                        <div class="card-body">
                            <form asp-controller="Access" asp-action="Login" method="post">
                                <div class="mb-4">
                                    <label class="mb-2" for="Email">Email</label>
                                    <input id="Email" class="form-control" type="text" placeholder="mail@abc.com" required asp-for="Email" />
                                </div>
                                <div class="mb-4">
                                    <label class="mb-2" for="Password">Password</label>
                                    <input id="Password" class="form-control" type="password" placeholder="password" required asp-for="Password" />
                                </div>
                                <div class="d-grid gap-2 mb-3">
                                    <button class="btn btn-primary" type="submit">Login</button>
                                </div>

                                @if (ViewData["Message"] != null)
                                {
                                    <div class="alert alert-danger" role="alert">
                                        @ViewData["Message"]
                                    </div>
                                }

                                <p class="mt-5 text-center registered">
                                    Not Registered Yet? <a asp-controller="Access" asp-action="Signup">Create an account</a>
                                </p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>  

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

Views/Access/Signup.cshtml
@model magaApp.ViewModels.UserViewModels;
@{
    Layout = null;
}

<html>
<head>
    <title>Signup</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="~/css/site.css" />

</head>

<body>


    <div class="container-fluid full-height">
        <div class="row h-100">
           
            <div class="d-none d-lg-block col-lg-6 p-0">
                <img src="~/images/banner.png" alt="Banner" class="img-fluid w-100 h-100" style="object-fit: cover;">
            </div>

          
            <div class="col-lg-6 col-12 d-flex align-items-center justify-content-center">
                <div class="col-lg-8 col-md-10 col-12">
                    <div class="">
                        <div class="card-header">
                            <h2 class="mb-3">Sig up</h2>
                            <p>See what is going on with your business</p>
                        </div>
                        <div class="card-body">
                            <form asp-controller="Access" asp-action="Signup" method="post">
                                <div class="mb-3">
                                    <label class="mb-2" for="FullName">Full Name</label>
                                    <input id="FullName" class="form-control" type="text" placeholder="Full Name" required asp-for="FullName" />
                                </div>
                                <div class="mb-3">
                                    <label class="mb-2" for="Email">Email</label>
                                    <input id="Email" class="form-control" type="text" placeholder="Email" required asp-for="Email" />
                                </div>
                                <div class="mb-3">
                                    <label class="mb-2" for="Password">Password</label>
                                    <input id="Password" class="form-control" type="password" placeholder="Password" required asp-for="Password" />
                                </div>
                                <div class="mb-3">
                                    <label class="mb-2" for="ConfirmPassword">Confirm Password</label>
                                    <input id="ConfirmPassword" class="form-control" type="password" placeholder="Confirm Password" required asp-for="ConfirmPassword" />
                                </div>
                                <div class="d-grid gap-2 mb-3">
                                    <button class="btn btn-primary" type="submit">Register now</button>
                                </div>

                                @if (ViewData["Message"] != null)
                                {
                                    <div class="alert alert-danger" role="alert">
                                        @ViewData["Message"]
                                    </div>
                                }

                                <p class="mt-5 text-center  registered">
                                    You have an account? <a asp-controller="Access" asp-action="Login">Log in</a>
                                </p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

Views/Home/Explorer.cshtml
@model List<magaApp.ViewModels.ExplorerViewModel>

@{
    ViewData["Title"] = "Explore Users";
}

<div class="container mt-5">
    <h1 class="text-center">Explore users and subscribe</h1>
    <div class="row mt-4">
        @foreach (var user in Model)
        {
            <div class="col-lg-3 col-md-6 mb-4">
                   
                    <div class="user-profile">
                        
                    </div>
                    @* <p class="card-text">@user.Email</p> *@


                    <div class="d-flex justify-content-between">
                    <div class="user-avatar">@user.Initials</div>

                    <button class="btn btn-primary">subscribe</button>
                    </div>
                    
            </div>
        }
    </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="mt-5">
    <div class="row">
       
        <div class="col-lg-3 col-md-6 mb-4">
            <div class="card">
                <div class="border-left-primary">
                    <div class="card-body">
                        <h5 class="card-title text-primary">Total magazines</h5>
                        <p class="card-text">Content for the first card.</p>
                    </div>
                </div>
            </div>
        </div>

       
        <div class="col-lg-3 col-md-6 mb-4">
            <div class="card">
                <div class="border-left-success">
                    <div class="card-body">
                        <h5 class="card-title text-success">Subscribed to accounts</h5>
                        <p class="card-text">Content for the second card.</p>
                    </div>
                </div>
            </div>
        </div>

        
        <div class="col-lg-3 col-md-6 mb-4">
            <div class="card">
                <div class="border-left-info">
                    <div class="card-body">
                        <h5 class="card-title text-info">Your magazines</h5>
                        <p class="card-text">Content for the third card.</p>
                    </div>
                </div>
            </div>
        </div>


       
        <div class="col-lg-3 col-md-6 mb-4">
            <div class="card">
                <div class="border-left-warning">
                    <div class="card-body">
                        <h5 class="card-title text-warning">Your subscribers</h5>
                        <p class="card-text">20</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12 mb-4">
            <div class="card card-maga" style="min-height: 500px;">
                <div class="card-body d-flex flex-column justify-content-center align-items-center">
                    <h5 class="card-title text-center">Share your magazines with the world</h5>
                    <form asp-controller="Magazine" asp-action="Upload" method="post" enctype="multipart/form-data">
                        <div class="mb-3">
                            <label for="pdfFile" class="btn btn-primary ">
                                Select a PDF magazine
                                <input type="file" class="form-control-file d-none" id="pdfFile" name="pdfFile" accept=".pdf" required>
                            </label>
                        </div>
                    </form>
                </div>
            </div>


        </div>




        All your magazines
    </div>




    @if (ViewData["Message"] != null)
    {
        <div class="alert alert-info" role="alert">
            @ViewData["Message"]
        </div>
    }


</div>

<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

Views/Home/UserMagazines.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - magaApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/magaApp.styles.css" asp-append-version="true" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:ital,opsz,wght@0,6..12,200..1000;1,6..12,200..1000&display=swap" rel="stylesheet">


</head>
<body>
    <header >
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 ">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">magaApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Explorer">Explore</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>

                    <div class="d-flex justify-content-between align-items-center gap-3">
                        <a class=" text-dark" asp-area="" asp-controller="Home" asp-action="GoOut">Sign out</a>

                        <div class="text-center">
                            @if (User.Identity!.IsAuthenticated)
                            {
                                <span class="rounded-initials">
                                    @{
                                        var fullName = User.Claims.Where(c => c.Type == ClaimTypes.Name).Select(c => c.Value).SingleOrDefault();
                                        if (!string.IsNullOrEmpty(fullName))
                                        {
                                            var names = fullName.Split(' ');
                                            var initials = names.Length > 1 ? $"{names[0][0]}{names[1][0]}" : names[0].Substring(0, 1);
                                            @initials
                                        }
                                    }
                                </span>
                            }
                        </div>
                    </div>

                    
                </div>

               
            </div>

            @using System.Security.Claims;
            @{
                ViewData["Title"] = "Home Page";
            }
            
            


        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @* <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - magaApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>